encoder:
  name: h264_nvenc

  options:
    preset: p6
    tune: ull
    delay: 0
    zerolatency: 1

  fps: 30
  keyframe_every: 60 # frames

input_topic: '/color/image_raw'
output_topic: '/color/packet'